[package]
name = "streetwarp"
version = "0.1.0"
authors = ["Peter Elmers <peter.elmers@yahoo.com>"]
edition = "2024"

[dependencies]
gpx = "0.10.0"
geo = "0.33"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
reqwest = "0.13"
futures = "0.3"
rayon = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
ordered-float = "5"
fs_extra = "1.3"
